### ISSUE TITLE
Entering players

### ISSUE THREAD

**Issue by Nelsonmac41** [rementis/LightningChipTourney#2]
I can only enter 2 players then it reverter back to start page

**Comment by rementis** [comment]
Can you provide more details?

Are you using N key to enter brand new players?

After two players, what do you mean by "start page"?

Any chance you can provide screenshots?

**Comment by Nelsonmac41** [comment]
It gos back to the start page and the 2 i entered disapear


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rementis** [comment]
Can you provide screen shots?  What names are you using for the players?  Any more details?

**Comment by Nelsonmac41** [comment]
I have got it to work not sure what I was doing wrong but works now

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rementis** [comment]
Awesome, let me know of any problems.  :)

**Comment by rementis** [comment]
.
