### ISSUE TITLE
Importing players with FargoID

### ISSUE THREAD

**Issue by psueric** [rementis/LightningChipTourney#5]
I've got fargoIDs for all the players who I want to enter into a tournament.
I'm loading players via spreadsheet to simplify player entry.
I downloaded the sample XLS file, which has 4 columns: Name, Fargo, Chips, Phone.
This file works fine to import multiple players into the tournament software.
The Fargo column appears to be "fargo rating" not "Fargo ID".
Is there any way to add the Fargo ID column to this spreadsheet so that the players are entered into with an associated Fargo ID.
Currently, I have to open the final spreadsheet and do an excel xlookup to match the player name with Fargo ID.
This isn't too difficult, but for a small glitch where the player name in the output spreadsheet usually ends with a single space.
This makes for a slight challenge getting the xlookup to match (unless my player name also has a single space in my lookup table)

Thanks in advance for your assistance.

**Comment by rementis** [comment]
I will fix the player space issue.  The format of the xls is what they requested to submit matches.  Is there some reason you also want to document the Fargo ID?

Dec 14, 2024 2:35:16 PM psueric ***@***.***>:

**Comment by rementis** [comment]
Please download version 10.61 and new XLS file.  You can now record Fargo ID.  Thanks!

**Comment by rementis** [comment]
Please download version 10.61 and new XLS file.  You can now record Fargo ID.  Thanks!
